//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblog.Core.DataAccess.Weblog
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdministratorSettings
    {
        public string SiteName { get; set; }
        public bool AllowComments { get; set; }
        public string WelcomeMailSubject { get; set; }
        public string WelcomeMailText { get; set; }
        public string PasswordChangeMailSubject { get; set; }
        public string PasswordChangeMailText { get; set; }
        public string OptInMailSubject { get; set; }
        public string OptInMailText { get; set; }
        public string SiteFooterText { get; set; }
        public string SiteKeywords { get; set; }
        public string SmtpServer { get; set; }
        public string SmtpUser { get; set; }
        public string SmtpPassword { get; set; }
        public bool SmtpRegisterAtServerNeeded { get; set; }
        public System.Guid ID { get; set; }
        public int FullEntriesPerSite { get; set; }
        public int EntriesPerSite { get; set; }
    }
}
