//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblog.Core.DataAccess.Weblog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Entries = new HashSet<Entry>();
        }
    
        public int CategoryID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Entry> Entries { get; set; }
    }
}
