//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblog.Core.DataAccess.Weblog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public Entry()
        {
            this.Categories = new HashSet<Category>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int EntryID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int AuthorID { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
