//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weblog.Core.DataAccess.Weblog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Entries = new HashSet<Entry>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserNameLowercase { get; set; }
        public string Email { get; set; }
        public string EmailLowercase { get; set; }
        public Nullable<int> EntrysPerSite { get; set; }
    
        public virtual ICollection<Entry> Entries { get; set; }
    }
}
